<?xml version="1.0" encoding="utf-8"?><Database Name="dbCours20172018" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1\SQLEXPRESS;Initial Catalog=dbCours20172018;Integrated Security=True" SettingsObjectName="FactureExamen.Properties.Settings" SettingsPropertyName="dbCours20172018ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllClients" Method="GetAllClients">
    <ElementType Name="GetAllClientsResult">
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FactureNombre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FactureNombreNonAquit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetClientFacture" Method="GetClientFacture">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetClientFactureResult">
      <Column Name="FactureID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Montant" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Acquit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>