#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevisionWPFFActures
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Revision")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::RevisionWPFFActures.Properties.Settings.Default.RevisionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllClients")]
		public ISingleResult<GetAllClientsResult> GetAllClients()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllClientsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllFacturesByClient")]
		public ISingleResult<GetAllFacturesByClientResult> GetAllFacturesByClient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> clientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID);
			return ((ISingleResult<GetAllFacturesByClientResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetAllClientsResult
	{
		
		private string _Nom;
		
		private System.Guid _ClientId;
		
		private System.Nullable<int> _FactureNombre;
		
		private System.Nullable<int> _FactureNombreNonAquit;
		
		public GetAllClientsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					this._ClientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactureNombre", DbType="Int")]
		public System.Nullable<int> FactureNombre
		{
			get
			{
				return this._FactureNombre;
			}
			set
			{
				if ((this._FactureNombre != value))
				{
					this._FactureNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactureNombreNonAquit", DbType="Int")]
		public System.Nullable<int> FactureNombreNonAquit
		{
			get
			{
				return this._FactureNombreNonAquit;
			}
			set
			{
				if ((this._FactureNombreNonAquit != value))
				{
					this._FactureNombreNonAquit = value;
				}
			}
		}
	}
	
	public partial class GetAllFacturesByClientResult
	{
		
		private System.Nullable<System.Guid> _ClientID;
		
		private System.Guid _FatctureID;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _Montant;
		
		private System.Nullable<bool> _Acquit;
		
		public GetAllFacturesByClientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatctureID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid FatctureID
		{
			get
			{
				return this._FatctureID;
			}
			set
			{
				if ((this._FatctureID != value))
				{
					this._FatctureID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montant", DbType="Float")]
		public System.Nullable<double> Montant
		{
			get
			{
				return this._Montant;
			}
			set
			{
				if ((this._Montant != value))
				{
					this._Montant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acquit", DbType="Bit")]
		public System.Nullable<bool> Acquit
		{
			get
			{
				return this._Acquit;
			}
			set
			{
				if ((this._Acquit != value))
				{
					this._Acquit = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
